default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: user
  password: password

development:
  <<: *default
  database: scim-development

test:
  <<: *default
  database: scim-test

production:
  <<: *default
  database: scim-production
